apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Override replicas to 3 for production
replicas:
  - name: orion-lms-deployment
    count: 3

# Common label for production
labels:
  - pairs:
      environment: production
    includeTemplates: true
    includeSelectors: true
