apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Override replicas to 1 for staging
replicas:
  - name: orion-lms-deployment
    count: 1

# Common label for staging
commonLabels:
  environment: staging
